# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Alert Scoring Agent - Main agent module.

Defaults to code-based pipeline (AlertScoringPipeline).
Falls back to LLM coordinator when USE_CODE_INSIGHTS=false.

Feature flag: USE_CODE_INSIGHTS (env var, default "true")
"""

import os
import json
from typing import AsyncGenerator

from google.adk import Agent
from google.adk.agents.base_agent import BaseAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events.event import Event
from google.adk.events.event_actions import EventActions
from google.adk.planners import BuiltInPlanner
from google.genai import types

from config.model_loader import get_agent_model, get_agent_thinking_config
from .prompt import ALERT_SCORING_INSTRUCTION
from .tools import (
    extract_alerts_from_analysis,
    get_supplementary_data_for_period,
    get_top_entities_by_metric,
    get_period_aggregates_by_dimension,
    score_alerts,
    apply_suppression,
)
from .tools.compute_severity import compute_severity

USE_CODE_INSIGHTS = os.environ.get("USE_CODE_INSIGHTS", "true").lower() == "true"


class AlertScoringPipeline(BaseAgent):
    """Code-based alert scoring pipeline — replaces the LLM coordinator.

    Runs the fixed 4-step pipeline in Python:
      extract_alerts -> apply_suppression -> score_alerts -> compute_severity

    No LLM call is made. The formatted prose summary is templated from the
    scored data rather than generated by an LLM.
    """

    def __init__(self):
        super().__init__(name="alert_scoring_coordinator")

    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        print(f"\n[AlertScoringPipeline] Starting code-based alert scoring...", flush=True)

        stats_json = ctx.session.state.get("statistical_summary", "{}")
        analysis_target = (
            ctx.session.state.get("current_analysis_target")
            or "unknown"
        )
        contract = ctx.session.state.get("dataset_contract")

        # ------------------------------------------------------------------ #
        # Step 1: Extract alerts from statistical summary
        # ------------------------------------------------------------------ #
        try:
            raw_alerts_json = await extract_alerts_from_analysis(
                statistical_summary=stats_json,
                analysis_target=analysis_target,
                contract=contract,
            )
            raw_alerts = json.loads(raw_alerts_json)
        except Exception as exc:
            self._store_error(ctx, f"extract_alerts_from_analysis failed: {exc}")
            yield Event(
                invocation_id=ctx.invocation_id,
                author=self.name,
                actions=EventActions(state_delta={
                    "alert_scoring_result": json.dumps({"error": str(exc), "alerts": []})
                }),
            )
            return

        if "error" in raw_alerts:
            self._store_error(ctx, raw_alerts["error"])
            yield Event(
                invocation_id=ctx.invocation_id,
                author=self.name,
                actions=EventActions(state_delta={
                    "alert_scoring_result": raw_alerts_json
                }),
            )
            return

        alerts = raw_alerts.get("alerts", [])
        print(f"[AlertScoringPipeline] Extracted {len(alerts)} raw alerts")

        if not alerts:
            empty_result = json.dumps({
                "analysis_type": "alert_scoring",
                "total_alerts_received": 0,
                "total_alerts_scored": 0,
                "high_priority_count": 0,
                "medium_priority_count": 0,
                "low_priority_count": 0,
                "top_alerts": [],
                "severity": {
                    "severity_score": 0.0,
                    "threshold_detail": "No actionable alerts detected.",
                    "high_priority_count": 0,
                    "medium_priority_count": 0,
                    "low_priority_count": 0,
                    "top_alert_score": 0.0,
                    "total_alerts": 0,
                }
            })
            yield Event(
                invocation_id=ctx.invocation_id,
                author=self.name,
                actions=EventActions(state_delta={"alert_scoring_result": empty_result}),
            )
            return

        # ------------------------------------------------------------------ #
        # Step 2: Apply suppression rules
        # ------------------------------------------------------------------ #
        try:
            suppression_input = json.dumps({
                "alerts": alerts,
                "dimension_value": analysis_target,
            })
            suppression_json = await apply_suppression(suppression_input)
            suppression_result = json.loads(suppression_json)
        except Exception as exc:
            print(f"[AlertScoringPipeline] WARNING: apply_suppression failed: {exc} — skipping")
            suppression_result = {
                "active_alerts": alerts,
                "suppressed_alerts": [],
                "suppression_stats": {"total_alerts": len(alerts), "suppressed_count": 0},
            }

        active_alerts = suppression_result.get("active_alerts", alerts)
        suppressed_alerts = suppression_result.get("suppressed_alerts", [])
        print(
            f"[AlertScoringPipeline] Suppression: {len(active_alerts)} active, "
            f"{len(suppressed_alerts)} suppressed"
        )

        # ------------------------------------------------------------------ #
        # Step 3: Score remaining alerts
        # ------------------------------------------------------------------ #
        try:
            score_input = json.dumps({
                "alerts": active_alerts,
                "config": {"top_n": 10, "min_score_threshold": 0.05},
            })
            scored_json = await score_alerts(score_input)
            scored_digest = json.loads(scored_json)
        except Exception as exc:
            self._store_error(ctx, f"score_alerts failed: {exc}")
            yield Event(
                invocation_id=ctx.invocation_id,
                author=self.name,
                actions=EventActions(state_delta={
                    "alert_scoring_result": json.dumps({"error": str(exc), "alerts": active_alerts})
                }),
            )
            return

        if "error" in scored_digest:
            yield Event(
                invocation_id=ctx.invocation_id,
                author=self.name,
                actions=EventActions(state_delta={"alert_scoring_result": scored_json}),
            )
            return

        # ------------------------------------------------------------------ #
        # Step 4: Compute severity
        # ------------------------------------------------------------------ #
        severity = compute_severity(scored_digest)

        # ------------------------------------------------------------------ #
        # Combine and store
        # ------------------------------------------------------------------ #
        final_result = {
            **scored_digest,
            "severity": severity,
            "suppression_summary": suppression_result.get("suppression_stats", {}),
            "suppressed_alerts": suppressed_alerts,
        }
        result_json = json.dumps(final_result, indent=2)

        print(
            f"[AlertScoringPipeline] Complete: "
            f"severity={severity['severity_score']:.3f}, "
            f"high={severity['high_priority_count']}, "
            f"medium={severity['medium_priority_count']}, "
            f"low={severity['low_priority_count']}\n"
        )

        yield Event(
            invocation_id=ctx.invocation_id,
            author=self.name,
            actions=EventActions(state_delta={"alert_scoring_result": result_json}),
        )

    @staticmethod
    def _store_error(ctx: InvocationContext, msg: str) -> None:
        print(f"[AlertScoringPipeline] ERROR: {msg}")


# ---------------------------------------------------------------------------
# LLM fallback: original wrapper (used when USE_CODE_INSIGHTS=false)
# ---------------------------------------------------------------------------

_alert_thinking = get_agent_thinking_config("alert_scoring_coordinator")
_base_agent = Agent(
    model=get_agent_model("alert_scoring_coordinator"),
    name="alert_scoring_coordinator_llm",
    description="Scores and prioritizes findings by financial impact and confidence. [Requires: analysis results or list of anomalies]",
    instruction=ALERT_SCORING_INSTRUCTION,
    tools=[
        extract_alerts_from_analysis,
        apply_suppression,
        score_alerts,
        get_supplementary_data_for_period,
        get_top_entities_by_metric,
        get_period_aggregates_by_dimension,
    ],
    output_key="alert_scoring_result",
    generate_content_config=types.GenerateContentConfig(
        response_modalities=["TEXT"],
        temperature=0.1,
    ),
    **({"planner": BuiltInPlanner(thinking_config=_alert_thinking)} if _alert_thinking else {}),
)


class AlertScoringWrapper(BaseAgent):
    """Wrapper to inject analysis results into the alert scoring agent context (fallback)."""

    def __init__(self, wrapped_agent):
        super().__init__(name="alert_scoring_coordinator")
        object.__setattr__(self, "wrapped_agent", wrapped_agent)

    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        from google.genai.types import Content, Part

        print(f"[ALERT_SCORING] Starting LLM alert scoring coordinator (fallback)")

        narrative_result = ctx.session.state.get("narrative_result", "No narrative result available.")
        da_result = ctx.session.state.get("data_analyst_result", "No data analyst result available.")
        stats_result = ctx.session.state.get("statistical_summary", "No statistical summary available.")

        injection_message = f"""Here are the analysis results to score and prioritize:

NARRATIVE_RESULT:
{narrative_result}

DATA_ANALYST_RESULT:
{da_result}

STATISTICAL_SUMMARY:
{stats_result}

Please extract alerts from these results, score them, and provide a prioritized list of findings."""

        ctx.session.events.append(Event(
            invocation_id="alert_injection",
            author="user",
            content=Content(role="user", parts=[Part(text=injection_message)]),
        ))

        async for event in self.wrapped_agent.run_async(ctx):
            yield event


# ---------------------------------------------------------------------------
# Export root_agent based on feature flag
# ---------------------------------------------------------------------------

root_agent = AlertScoringPipeline() if USE_CODE_INSIGHTS else AlertScoringWrapper(_base_agent)

print(
    f"[AlertScoring] Using "
    f"{'code-based pipeline' if USE_CODE_INSIGHTS else 'LLM coordinator'} "
    f"(USE_CODE_INSIGHTS={USE_CODE_INSIGHTS})"
)


