from typing import List, Dict, Any, AsyncGenerator
from google.adk.agents.base_agent import BaseAgent
from google.adk.agents.parallel_agent import ParallelAgent
from google.adk.agents.invocation_context import InvocationContext
from google.adk.events.event import Event
from google.adk.events.event_actions import EventActions
import importlib
import time
from ..utils.timing_utils import TimedAgentWrapper
from ..utils.json_utils import safe_parse_json

class DynamicParallelAnalysisAgent(BaseAgent):
    """
    Spawns and executes analysis agents in parallel based on the plan generated by PlannerAgent.
    """
    _agent_registry: Dict[str, str] = {
        "hierarchical_analysis_agent": "data_analyst_agent.sub_agents.hierarchical_analysis_agent.agent",
        "statistical_insights_agent": "data_analyst_agent.sub_agents.statistical_insights_agent.agent",
        "seasonal_baseline_agent": "data_analyst_agent.sub_agents.seasonal_baseline_agent.agent",
    }
    
    def __init__(self):
        super().__init__(name="dynamic_parallel_analysis")

    def _get_agent_instance(self, name: str) -> BaseAgent:
        module_path = self._agent_registry.get(name)
        if not module_path:
            raise ValueError(f"Agent {name} not found in registry.")
        
        module = importlib.import_module(module_path)
        return module.root_agent

    async def _run_async_impl(self, ctx: InvocationContext) -> AsyncGenerator[Event, None]:
        plan_raw = ctx.session.state.get("execution_plan", {})
        plan_result = safe_parse_json(plan_raw)

        # Support both JSON-dict plans and direct list plans.
        selected_agent_infos = plan_result.get("selected_agents", [])
        if not selected_agent_infos and isinstance(plan_raw, list):
            selected_agent_infos = plan_raw
        
        # Filter for agents that are in our registry and intended for parallel execution
        # (alert_scoring_coordinator is usually sequential at the end)
        parallel_agents = []
        for info in selected_agent_infos:
            name = info.get("name")
            if name in self._agent_registry:
                try:
                    agent = self._get_agent_instance(name)
                    # Wrap with timing to track bottlenecks in parallel execution
                    parallel_agents.append(TimedAgentWrapper(agent))
                except Exception as e:
                    print(f"[DynamicParallelAnalysis] Warning: Failed to load agent {name}: {e}")

        if not parallel_agents:
            print("[DynamicParallelAnalysis] No parallel agents selected by planner.")
            yield Event(invocation_id=ctx.invocation_id, author=self.name, actions=EventActions())
            return

        print(f"[DynamicParallelAnalysis] Executing {len(parallel_agents)} agents in parallel: {[a.name for a in parallel_agents]}")
        
        # Clear parents to avoid ADK validation errors during re-runs
        for agent in parallel_agents:
            if hasattr(agent, 'parent') and agent.parent is not None:
                object.__setattr__(agent, 'parent', None)

        # Create a temporary ParallelAgent and run it
        parallel_runner = ParallelAgent(
            name="inner_parallel_analysis",
            sub_agents=parallel_agents
        )
        
        async for event in parallel_runner.run_async(ctx):
            yield event
