"""Data quality & notes section."""

from __future__ import annotations

from typing import List


def build_data_quality_section(
    *,
    levels_analyzed: list[int],
    drill_down_path: str,
    temporal_grain: str,
    short_delta_label: str,
    lag_meta: dict | None,
    util_ratios: list,
    util_summary: dict,
) -> List[str]:
    lines: List[str] = ["## Data Quality & Notes", ""]

    if lag_meta and lag_meta.get("lag_window"):
        window = lag_meta["lag_window"]
        lines.append("### [SUPPRESSED] Incomplete Data Window")
        lines.append(
            "Signals from the following periods were suppressed as data is still accumulating: "
            + ", ".join(window)
        )
        lines.append("")

    lines.append(f"- Analysis completed successfully with {len(levels_analyzed)} hierarchy levels")
    lines.append(f"- Drill-down path: {drill_down_path}")
    lines.append(f"- Temporal grain detected as {temporal_grain} (comparisons interpreted as {short_delta_label})")
    lines.append("- All variance calculations use category-specific materiality thresholds")

    if util_ratios:
        metrics_computed = util_summary.get("metrics_computed", 0) if isinstance(util_summary, dict) else 0
        lines.append(f"- Utilization analysis: {len(util_ratios)} periods, {metrics_computed} metrics")
        lines.append("- Data source: Ops Metrics DS via A2A")

    lines.append("")
    lines.append("---")
    lines.append("*This report was auto-generated by Data Analyst Agent*")
    return lines
