source:
  file: "data/public/owid_co2_data.csv"
  encoding: "utf-8"
  delimiter: ","
  format: "long"

sort_columns: ["year", "country"]

output_columns:
  - "year"
  - "country"
  - "co2"
  - "coal_co2"
  - "gas_co2"
  - "oil_co2"
