source:
  file: "data/public/owid_co2_data.csv"
  encoding: "utf-8"
  delimiter: ","
  format: "long"

sort_columns: ["year", "country"]

output_columns:
  - "country"
  - "year"
  - "iso_code"
  - "population"
  - "gdp"
  - "co2"
  - "co2_per_capita"
