metrics:
  co2:
    unit: "MtCO2"
  coal_co2:
    unit: "MtCO2"
  gas_co2:
    unit: "MtCO2"
  oil_co2:
    unit: "MtCO2"
  co2_per_capita:
    unit: "tonnes per capita"
  population:
    unit: "people"
  gdp:
    unit: "USD"
